version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: "event-ms-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_service
    ports:
      - "5434:5432"
  redis:
    image: redis:latest
    restart: always
    container_name: "event-ms-redis"
    ports:
      - "6381:6379"
  redis-test:
    image: redis:latest
    restart: always
    container_name: "event-ms-redis-test"
    ports:
      - "6382:6379"
