version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: "rust-server-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_service
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    restart: always
    container_name: "rust-server-redis"
    ports:
      - "6381:6379"
  redis-test:
    image: redis:latest
    restart: always
    container_name: "rust-server-redis-test"
    ports:
      - "6382:6379"